### PR TITLE
Use newer Easymport APIs

### PR DESCRIPTION
**Pull request by mickaelistria**
+ Automated test
+ Move classes to internal

### CODE REVIEW

**Comment by paulvi** [comment]
I guess "Move classes to internal" is done to make it better when switching to easyimport as external ?

**Comment by mickaelistria** [comment]
It's mostly done because I needed to export the classes to write the test, but I don't want anyone to think those are APIs they can rely one.

**Comment by paulvi** [comment]
Aren't they become something open?

**Comment by mickaelistria** [comment]
Thym implementation of Easymport API are not meant to be made open to extenders. However, we can reconsider it if you explain a real-world interesting use-case.

**Comment by paulvi** [comment]
I may be not exact, but isn't there already Eclipse project proposal to use "Smart Import framework"

https://wiki.eclipse.org/E4/UI/Smart_Import

**Comment by mickaelistria** [comment]
The smart import is an IDE-wide API and extension point and some UI entry point to import a project and automatically allow to detect its type and apply necessary configuration steps to make it ready to use after import. It's currently a separate plugin, but it should become core Platform-UI for Neon.
The Smart Import API and extension point are public, although still evolving, and can be implemented/extended by any project. This is a Thym implemtation/extension for Smart Import to provide easy import of Cordova project. Athough, the Smart Import framework is public, the Thym implementation is not meant to be considered as an API at this moment.

**Comment by mickaelistria** [comment]
@gorkem did you have the opportunity to consider merging it?

**Comment by gorkem** [comment]
@mickaelistria org.eclipse.thym.ui.importer.test seems to be missing the pom.xml

**Comment by mickaelistria** [comment]
@gorkem I updated the PR so the test now works. However, the importer adds a dependency on Eclipse Mars (because it uses JobGroup API). Would you mind making Mars the default target?

**Comment by gorkem** [comment]
Not at all it is time to move to Mars target anyway

**Pull request merged**
