### PR TITLE
[515710] Add apache.http to required bundles and remove unused depend…

### PR DESCRIPTION
**Pull request by rawagner**
…encies.

Bug:https://bugs.eclipse.org/bugs/show_bug.cgi?id=515710
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=515710

**Comment by rawagner** [comment]
@psrna can you try the patch please ?

**Comment by psrna** [comment]
Error message is gone now. But I'm getting new error, which I didn't in the previous build.
The message is: "Could not find *-Info.plist file, or config.xml file." which prevents me to finish the cordova plugin dialog.

`[screenshot
](https://www.dropbox.com/s/lytledoc1b9dxnz/Screenshot%202017-04-25%2011.33.59.png?dl=0)`

**Comment by psrna** [comment]
It turned out the above problem is a separate issue. I'll file another BZ for that.

This patch is good to go.

**Pull request merged**
