### PR TITLE
Bug 488701 - app dose not lanuch when run emulator for Android

### PR DESCRIPTION
**Pull request by wnjin**
This bug due to the code on line 53 "String name = project.getBuildArtifactAppName();"
The value of "name" should be activity class but actually it returns app name. Is there any existed interface in THYM to get the activity class?

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=488701

**Comment by gorkem** [comment]
Is this going to break old cordova-android versions?. If I remember correctly the earlier cordova-android builds actually set activity name to AppName and that is why Thym adopted the same strategy.

**Comment by gorkem** [comment]
Can you also add a Signed-Off-By footer to your commit message

**Comment by wnjin** [comment]
I just signed the CLA at Eclipse website. But it still shows I need to confirm the origin of submission.

**Comment by wnjin** [comment]
Thanks for reply. I am not sure about the old cordova-android versions. So seems the new version cordova-android changed the activity class name to 'MainActivity'? Shall we support this? We can find the activity class at AndroidMenifest.xml, is there already any interface to access it?

**Comment by gorkem** [comment]
Eclipse rules require a Signed-Off-By footer on every commit message, can you squash your commits into a single one and keep the Signed-Off footer.

**Pull request closed without merging**
