### PR TITLE
[491242] CordovaPluginSelectionPage performance issues

### PR DESCRIPTION
**Pull request by rawagner**
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=491242
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=455445
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=491242

**Comment by rawagner** [comment]
cordova_page

screenshot of new CordovaPluginSelectionPage

**Comment by gorkem** [comment]
Wow, this looks great. I will try to review this ASAP.

**Comment by rawagner** [comment]
@gorkem  have you had a chance to look at it ? I would not mind to implement any changes, if requested. Thanks!

**Comment by rawagner** [comment]
@gorkem This is not happening on Linux (thats why I missed it), but on OSX and Windows. I also fixed the treeviewer to not show the empty last column (also not happening on Linux). Fixed and tested on all platforms

**Comment by rawagner** [comment]
@gorkem can you please take a look again ? I've updated the PR and tested on Windows/OSX/Linux

**Pull request merged**
